# =========================
# PDF Preview
# =========================
[[previewer]]
name = "pdf"
mime = "application/pdf"
run = '''
pdftoppm -png -scale-to 1024 -f 1 -l 1 "$1" |
convert png:- png:-
'''

